name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - staging
      - dev

jobs:
  trivy-scan-fs:
    name: Scan Repository for Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-fs-results.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-fs-results.sarif'

  build-scan-push:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker image tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "BUILD_TAG=$(git describe --tags --abbrev=0 || echo v1.0.0)" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "BUILD_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi
          echo "Build tag set to: $BUILD_TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t taufiq14s/voting-apps-result-frontend:${{ env.BUILD_TAG }} -f ./Dockerfile .
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            docker tag taufiq14s/voting-apps-result-frontend:${{ env.BUILD_TAG }} taufiq14s/voting-apps-result-frontend:latest
          fi

      - name: Run Trivy vulnerability scanner on Docker image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'image'
          image-ref: 'taufiq14s/voting-apps-result-frontend:${{ env.BUILD_TAG }}'
          format: 'table'
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker Image
        run: |
          docker push taufiq14s/voting-apps-result-frontend:${{ env.BUILD_TAG }}
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            docker push taufiq14s/voting-apps-result-frontend:latest
          fi
